# Generated by Django 5.2.17 on 2026-09-08 09:30

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='name',
            field=models.CharField(help_text='Academic Year (e.g. 2026-2027)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course Code (e.g. BTECH-CSE)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='Associated Engineering Branch', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Branch Code (e.g. CSE, ECE, EEE, IT, CIVIL, AIDS)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Department / Branch Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Subject Code', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='teacher_id',
            field=models.CharField(help_text='Unique Faculty ID (e.g. T101)', max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='TeacherAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(default=datetime.date.today)),
                ('status', models.CharField(choices=[('Present', 'Present'), ('Absent', 'Absent'), ('On Leave', 'On Leave')], default='Present', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.teacherprofile')),
            ],
            options={
                'db_table': 'teacher_attendance',
                'ordering': ['-attendance_date'],
            },
        ),
    ]
