# Generated by Django 5.2.17 on 2026-09-08 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_number',
            field=models.PositiveIntegerField(help_text='Semester Number (e.g. 1, 2, 3, 4)'),
        ),
        migrations.CreateModel(
            name='StudentFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Invoice Title (e.g. Semester 1 Tuition Fee)', max_length=100)),
                ('fee_type', models.CharField(choices=[('TUITION', 'Tuition Fee'), ('ADMISSION', 'Admission Fee'), ('EXAM', 'Examination Fee'), ('HOSTEL', 'Hostel Fee'), ('OTHER', 'Other / Miscellaneous')], default='TUITION', max_length=20)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total fee amount', max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount paid so far', max_digits=10)),
                ('due_date', models.DateField(help_text='Payment due date')),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PARTIAL', 'Partially Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=20)),
                ('payment_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.academicyear')),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.course')),
                ('student', models.ForeignKey(help_text='Student account', on_delete=django.db.models.deletion.CASCADE, related_name='fee_invoices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_fees',
                'ordering': ['-due_date'],
            },
        ),
    ]
