# Generated by Django 5.2.17 on 2026-09-09 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_academicyear_name_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='year',
            field=models.CharField(choices=[('I', 'I Year'), ('II', 'II Year'), ('III', 'III Year'), ('IV', 'IV Year')], default='I', help_text='B.Tech Academic Year (I, II, III, IV)', max_length=10),
        ),
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(help_text='Course Code (e.g. BTECH-ECE)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='department',
            field=models.ForeignKey(help_text='Associated Engineering Stream', on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='core.department'),
        ),
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(help_text='Stream Code (e.g. ECE, CSE, IT, EEE, CIVIL, AIDS)', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(help_text='Department / Stream Name', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='title',
            field=models.CharField(help_text='Invoice Title (e.g. Semester 1 B.Tech Tuition Fee)', max_length=100),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Admission Serial Number', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.course'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='core.department'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='student_id',
            field=models.CharField(help_text='Roll No (e.g. ECE: 22691A0401, CSE: 22691A0501)', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='core.department'),
        ),
    ]
