# Generated by Django 5.2.17 on 2026-09-10 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_studentprofile_year_alter_course_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammark',
            name='semester',
            field=models.CharField(choices=[('Sem I', 'Sem I'), ('Sem II', 'Sem II')], default='Sem I', help_text='Semester (e.g. Sem I, Sem II)', max_length=20),
        ),
        migrations.AddField(
            model_name='exammark',
            name='subject_code',
            field=models.CharField(blank=True, help_text='Subject Code e.g. EC101', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='exammark',
            name='exam_name',
            field=models.CharField(default='End Semester Examination', help_text='e.g. Mid-term, End Semester Examination', max_length=100),
        ),
    ]
