# Generated by Django 5.2.17 on 2026-09-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exammark_semester_exammark_subject_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exammark',
            name='semester',
            field=models.CharField(choices=[('Sem I', 'Sem I'), ('Sem II', 'Sem II'), ('Sem III', 'Sem III'), ('Sem IV', 'Sem IV'), ('Sem V', 'Sem V'), ('Sem VI', 'Sem VI'), ('Sem VII', 'Sem VII'), ('Sem VIII', 'Sem VIII')], default='Sem I', help_text='Semester (e.g. Sem I, Sem II)', max_length=20),
        ),
    ]
