# Generated by Django 5.2.17 on 2026-09-10 11:59

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_exammark_semester'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentfee',
            name='semester',
            field=models.CharField(choices=[('Sem I', 'Sem I'), ('Sem II', 'Sem II'), ('Sem III', 'Sem III'), ('Sem IV', 'Sem IV'), ('Sem V', 'Sem V'), ('Sem VI', 'Sem VI'), ('Sem VII', 'Sem VII'), ('Sem VIII', 'Sem VIII')], default='Sem I', help_text='Semester (e.g. Sem I, Sem II)', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentfee',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('70000.00'), help_text='Standard B.Tech Fee (₹70,000)', max_digits=10),
        ),
    ]
